const Map<String, String> arSA = {
  'welcome': 'مرحبا',
  'login': 'تسجيل الدخول',
  'signup': 'انشاء حساب',
  'logout': 'تسجيل الخروج',
  'sign_technician': 'انشاء حساب فني؟',
  'forgot_password': 'نسيت كلمه المرور؟',
  'enter': 'ادخل',
  'email': 'البريد الالكتروني',
  'password': 'الرمز السري',
  'technician': 'الفنيين',
  'clients': 'العملاء',
  'services': 'الخدمات',
  'full_name': 'الاسم الكامل',
  'enter_valid_email': 'ادخل بريد الكتروني صحيح',
  'password_valid': 'يجب ان يتكون الرمز السري من ٦ احرف علي الاقل',
  'already_have_account': 'بالفعل تملك حساب؟',
  'should': 'يجب ان تقوم بادخل البريد الاكتروني',
  'check_email': 'افحص بريدك الاكتروني!',
  'send_request': 'ارسال طلب',
  'what_problem': 'ما هي المشكله',
  'date_time': 'التاريخ و الوقت',
  'no_tec_available_now': 'لا يوجد فني متوفر حاليا!',
  'request_send': 'تم ارسال الطلب بنجاح!',
  'my_requests': 'طلباتي',
  'pending': 'قيد الانتظار',
  'received': 'استلم',
  'working': 'يعمل',
  'complete': 'اكتمل',
  'write_something': 'اكتب شئ',
  'message': 'رساله',
  'send': 'ارسال',
  'no_request': 'لا يوجد طلبات متاحه لك!',
  'sending_review': 'ارسل التقييم',
  'no_review': 'لا يوجد تقييمات تمت اضافتها!',
  'choose_rate': 'اضف تقييم',
  'review': 'تقييم',
  'requests': 'الطلبات',
  'home_page':'الصفحه الرئيسيه',
  'language': 'English'
};
