const Map<String, String> enUS = {
  'welcome':'Welcome',
  'login':'Login',
  'signup':'Signup',
  'sign_technician':'Register as a technician?',
  'forgot_password':'Forgot Password?',
  'enter':'Enter',
  'email':'Email',
  'technician':'Technicians',
  'services':'Services',
  'logout':'Logout',
  'clients':'Clients',
  'password':'Password',
  'full_name':'Full Name',
  'enter_valid_email':'enter valid email',
  'password_valid':'password should be at least 6 characters minimum',
  'already_have_account':'Already have an account?',
  'should':'you should enter valid email',
  'check_email':'Check your email!',
  'send_request':'Send Request',
  'what_problem':'What is the problem',
  'date_time':'Date & Time',
  'no_tec_available_now':'there are no technician available for now!',
  'request_send':'Request has been send successfully!',
  'my_requests':'My Requests',
  'pending':'Pending',
  'received':'Received',
  'working':'Working',
  'complete':'Complete',
  'write_something':'Write Something',
  'message':'message',
  'send':'Send',
  'no_request':'There are no request for you!',
  'sending_review':'Send Review',
  'no_review':'There are no reviews added to you!',
  'choose_rate':'add rate!',
  'review':'Review',
  'requests':'Requests',
  'home_page':'Home Page',
  'language':'العربيه'

};
